In [1]:
#import cPickle
import cv2
import os
import numpy as np
import PIL
import glob
import matplotlib.pyplot as plt

In [2]:
#x=0
image_batch= []
for file in glob.glob("D:/Projects/Tracking Project/Datasets/UA-Detrac Dataset/Insight-MVT_Annotation_Train/MVI_20011/*.jpg"):
    image_batch.append([cv2.imread(file)])
    #x+=1
    #if x==10:
        #break

In [7]:
image_batch[663][0]

array([[[ 50,  54,  59],
        [ 50,  54,  59],
        [ 49,  53,  58],
        ...,
        [ 92,  91, 101],
        [ 92,  90, 102],
        [ 93,  91, 103]],

       [[ 46,  50,  55],
        [ 44,  48,  53],
        [ 41,  45,  50],
        ...,
        [ 93,  92, 102],
        [ 94,  92, 104],
        [ 95,  93, 105]],

       [[ 50,  54,  59],
        [ 50,  54,  59],
        [ 47,  51,  56],
        ...,
        [ 96,  94, 106],
        [ 96,  94, 106],
        [ 96,  94, 106]],

       ...,

       [[116, 125, 135],
        [ 90,  99, 109],
        [ 86,  95, 105],
        ...,
        [130, 135, 138],
        [129, 134, 137],
        [127, 132, 135]],

       [[114, 123, 133],
        [100, 109, 119],
        [ 91, 100, 110],
        ...,
        [129, 134, 137],
        [129, 134, 137],
        [128, 133, 136]],

       [[105, 114, 124],
        [103, 112, 122],
        [ 89,  98, 108],
        ...,
        [126, 131, 134],
        [128, 133, 136],
        [128, 133, 136]]

In [15]:
images[0]

array([[[ 66,  68,  78],
        [ 70,  72,  82],
        [ 69,  71,  81],
        ...,
        [118, 117, 133],
        [118, 117, 133],
        [118, 118, 132]],

       [[ 65,  67,  77],
        [ 70,  72,  82],
        [ 70,  72,  82],
        ...,
        [120, 120, 134],
        [120, 120, 134],
        [120, 120, 134]],

       [[ 63,  65,  75],
        [ 66,  68,  78],
        [ 66,  68,  78],
        ...,
        [120, 120, 134],
        [120, 120, 134],
        [120, 120, 134]],

       ...,

       [[ 71,  75,  86],
        [ 50,  54,  65],
        [ 44,  48,  59],
        ...,
        [119, 122, 126],
        [117, 120, 124],
        [126, 129, 133]],

       [[ 80,  84,  95],
        [ 54,  58,  69],
        [ 42,  46,  57],
        ...,
        [122, 125, 129],
        [132, 135, 139],
        [144, 147, 151]],

       [[ 83,  87,  98],
        [ 54,  58,  69],
        [ 38,  42,  53],
        ...,
        [132, 135, 139],
        [153, 156, 160],
        [147, 150, 154]]

In [37]:
img=cv2.imread('img00001.jpg')
img

array([[[ 62,  63,  77],
        [ 70,  72,  83],
        [ 69,  71,  82],
        ...,
        [111, 115, 133],
        [110, 114, 132],
        [110, 114, 132]],

       [[ 64,  66,  77],
        [ 69,  71,  82],
        [ 66,  68,  79],
        ...,
        [111, 115, 133],
        [110, 114, 132],
        [110, 114, 132]],

       [[ 63,  65,  76],
        [ 64,  66,  77],
        [ 60,  62,  73],
        ...,
        [112, 116, 134],
        [111, 115, 133],
        [111, 115, 133]],

       ...,

       [[ 43,  48,  57],
        [ 43,  48,  57],
        [ 80,  85,  94],
        ...,
        [108, 113, 116],
        [111, 116, 119],
        [132, 137, 140]],

       [[ 48,  54,  61],
        [ 43,  49,  56],
        [ 76,  82,  89],
        ...,
        [116, 121, 124],
        [124, 129, 132],
        [140, 145, 148]],

       [[ 47,  53,  60],
        [ 40,  46,  53],
        [ 72,  78,  85],
        ...,
        [139, 142, 146],
        [140, 143, 147],
        [136, 139, 143]]

In [54]:
img.shape

(540, 960, 3)

In [55]:
img.size

1555200

In [56]:
img.dtype

dtype('uint8')

In [65]:
cv2.imshow('arc', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
#crop_img = img[y:y+h, x:x+w]

In [64]:
cropped = img[200:800, 500:900]
cv2.imshow("cropped", cropped)
cv2.waitKey(0)

-1

In [42]:
dim= (800, 400)
resized = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
cv2.imshow("resized", resized)
cv2.waitKey(0)

-1

### Bbox Xml Parsing

In [32]:
import xml.etree.ElementTree as ET
tree = ET.parse('MVI_20011.xml')
root = tree.getroot()

In [4]:
frames = tree.findall('frame')
frames

[<Element 'frame' at 0x000002237FEE0C78>,
 <Element 'frame' at 0x000002237FEEE4A8>,
 <Element 'frame' at 0x000002237FEEEC78>,
 <Element 'frame' at 0x000002237FEF84A8>,
 <Element 'frame' at 0x000002237FEF8C78>,
 <Element 'frame' at 0x000002237FF004A8>,
 <Element 'frame' at 0x000002237FF00B88>,
 <Element 'frame' at 0x000002237FF092C8>,
 <Element 'frame' at 0x000002237FF099A8>,
 <Element 'frame' at 0x000002237FF110E8>,
 <Element 'frame' at 0x000002237FF117C8>,
 <Element 'frame' at 0x000002237FF11EA8>,
 <Element 'frame' at 0x000002237FF1C5E8>,
 <Element 'frame' at 0x000002237FF1CCC8>,
 <Element 'frame' at 0x000002237FF25408>,
 <Element 'frame' at 0x000002237FF25A48>,
 <Element 'frame' at 0x000002237FF2C0E8>,
 <Element 'frame' at 0x000002237FF2C728>,
 <Element 'frame' at 0x000002237FF2CD68>,
 <Element 'frame' at 0x000002237FF35408>,
 <Element 'frame' at 0x000002237FF35A48>,
 <Element 'frame' at 0x000002237FF3D0E8>,
 <Element 'frame' at 0x000002237FF3D728>,
 <Element 'frame' at 0x000002237FF

In [45]:
roi_recs = []
for ix, frame in enumerate(frames):
    density = frame.attrib['density'] # string '7'
    frame_num = frame.attrib['num'] # string '1'
    img_num = ''
    if len(frame_num) < 5:
                for iter_img_num in range(5-len(frame_num)):
                    img_num = '0'+img_num
                    img_num = img_num + frame_num
img_num

'00664664'

In [46]:
roi_rec = dict()

In [47]:
 im_size = cv2.imread('img00001.jpg').shape

In [48]:
im_size

(540, 960, 3)

In [49]:
roi_rec_height = float(im_size[0])
roi_rec_width = float(im_size[1])

In [50]:
target_list = frame.findall('target_list')
target_list

[<Element 'target_list' at 0x0000022301A82278>]

In [51]:
if len(target_list)>0:
    tl = target_list[0]
    targets = tl.findall('target')
    
targets
num_targets = len(targets)
num_targets

10

In [52]:
boxes = np.zeros((num_targets, 4), dtype=np.uint16)
boxes

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint16)

In [53]:
gt_classes = np.zeros((num_targets), dtype=np.int32)
gt_classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
classes = ['__background__',  # always index 0
                        'vehicle']

In [55]:
num_classes=len(classes)
num_classes

2

In [56]:
overlaps = np.zeros((num_targets, num_classes), dtype=np.float32)
overlaps

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [57]:
class_to_index = dict(zip(classes, range(num_classes)))
class_to_index

{'__background__': 0, 'vehicle': 1}

In [59]:
for ix, target in enumerate(targets):
		    bbox = target.find('box').attrib
		    # Make pixel indexes 0-based
		    x1 = float(bbox['left'])-1
		    y1 = float(bbox['top'])-1
		    x2 = x1 + float(bbox['width'])
		    y2 = y1 + float(bbox['height'])

		    #x1 = float(bbox.find('xmin').text) - 1
		    #y1 = float(bbox.find('ymin').text) - 1
		    #x2 = float(bbox.find('xmax').text) - 1
		    #y2 = float(bbox.find('ymax').text) - 1
		    #cls = class_to_index[obj.find('name').text.lower().strip()]
		    cls = class_to_index['vehicle']
		    boxes[ix, :] = [x1, y1, x2, y2]
		    gt_classes[ix] = cls
		    overlaps[ix, cls] = 1.0

		    roi_rec.update({'boxes': boxes,
		                'gt_classes': gt_classes,
		                'gt_overlaps': overlaps,
		                'max_classes': overlaps.argmax(axis=1),
		                'max_overlaps': overlaps.max(axis=1),
		                'flipped': False})
roi_recs.append(roi_rec)
roi_recs

[{'boxes': array([[456,  45, 481,  75],
         [497, 242, 608, 353],
         [461,  36, 538, 126],
         [536,  56, 568,  82],
         [624,  22, 651,  42],
         [665,  22, 692,  48],
         [590,  48, 626,  82],
         [574,  24, 607,  54],
         [533,  37, 567,  66],
         [826,  78, 894, 131]], dtype=uint16),
  'gt_classes': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
  'gt_overlaps': array([[0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.],
         [0., 1.]], dtype=float32),
  'max_classes': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
  'max_overlaps': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32),
  'flipped': False},
 {'boxes': array([[456,  45, 481,  75],
         [497, 242, 608, 353],
         [461,  36, 538, 126],
         [536,  56, 568,  82],
         [624,  22, 651,  42],
         [665,  22, 692,  48],
         [590,  48, 6